### ISSUE TITLE
次のリリースのバージョニング

### ISSUE THREAD

**Issue by munepi** [ketpic/kettex#1]
ketcindy versioning が無いので何か付けたい。最悪、「日付」でしょうか ;-) 

@s-takato 
先日のセミナーの作業により、現時点の ketpic/ketcindy で問題なく動くことを確認できました。

### Mac

 Mac 版のみ、Cinderella2.app がインストールされている前提で、
KeTTeX.app を実行するだけで、すぐに使えるようにします。
もう少し、KeTTeX.app アプリケーションの細かい挙動の制御もやりたいですけれども、
ひとまず最初現のみで「リリース」という形にさせてください。
追々、AppleScript で少し開発したいと存じます。

### Windows

ひとまず、KeTTeX の環境のみとさせてくださいませ。
こちらは上記Mac版のKeTTeX.app 同様に、
別途 KeTTeX.exe を開発して、ダブルクリックだけですぐに使えるようにしたいですね。
VBScript か PowerShell あたりで開発するのがよいでしょうか。

### Linux 

こちらは KeTTeXの環境のみで十分だと思います。

**Comment by s-takato** [comment]
高遠です．

はい，それでお願いします．
１／３１の納品が終わってからも修正は可能です．

よろしくお願いします．

**Comment by munepi** [comment]
> ketcindy versioning が無いので何か付けたい。最悪、「日付」でしょうか ;-)

ketcindy 本体のバージョンニング（現状、日付っぽい）ができるまで、KeTTeXのバージョニングを `v0.YYYYMMDD` （YYYYMMDD: ビルドした日付）としたいと思います。

**Comment by munepi** [comment]
closed #1 

1b97d37 を v0.20180124 としてリリースしました。
